version: '3'
services:
    doomsday_coffee_api:
        build: .
        restart: unless-stopped
        container_name: doomsday_coffee_api
        ports: 
            - "8080:8080"
        environment:
            APP_ENV: "prod"
            APP_DEBUG: "False"
            APP_PORT: 8080
            MONGODB_HOSTNAME: mongodb
        volumes:
        - .:/app
        depends_on:
        - mongodb
    instagramscraper:
        build: .
        command: python checker.py
        container_name: instagramscraper
        restart: unless-stopped
        environment: 
            MONGODB_HOSTNAME: mongodb
        volumes:
        - appdata:/app
        depends_on:
        - mongodb
    mongodb: 
        image: mongo:4.0.8
        container_name: mongodb
        ports: 
            - "27017:27017"
        restart: unless-stopped
        command: mongod
        environment:
            MONGO_INITDB_DATABASE: Doomsday_Coffee
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
        - mongodbdata:/data/db

    webserver:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: digitalocean.com/webserver:latest
        container_name: webserver
        restart: unless-stopped
        environment:
            APP_ENV: "prod"
            APP_NAME: "webserver"
            APP_DEBUG: "true"
            SERVICE_NAME: "webserver"
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - nginxdata:/var/log/nginx
        depends_on:
        - doomsday_coffee_api

volumes:
    mongodbdata:
        driver: local
    nginxdata:
        driver: local
    appdata:
        driver: local
        