version: '3'
services:
    api:
        build: .
        command: python -m flask run --host 0.0.0.0
        restart: unless-stopped
        container_name: Doomsday_Coffee_API
        ports: 
            - "5000:5000"
        environment:
            APP_ENV: "dev"
            APP_DEBUG: "True"
            MONGODB_HOSTNAME: mongodb
        volumes:
        - .:/app
        depends_on:
        - mongodb
    instagramscraper:
        build: .
        command: python checker.py
        container_name: instagramscraper
        restart: unless-stopped
        environment: 
            MONGODB_HOSTNAME: mongodb
        volumes:
        - .:/app
        depends_on:
        - mongodb
    mongodb: 
        image: mongo:4.0.8
        container_name: mongodb
        ports: 
            - "27017:27017"
        restart: unless-stopped
        command: mongod
        environment:
            MONGO_INITDB_DATABASE: Doomsday_Coffee
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
        - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local