name: Build and Publish Docker
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: python

    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
              pip install -r requirements.txt
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker-compose build
      - name: Push
        run: |
          docker-compose push ${{ secrets.DOCKER_USER }}/doomsdaycoffeeapi:${{ github.sha }}
          docker-compose push ${{ secrets.DOCKER_USER }}/doomsdaycoffeeapi:latest
